<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\portfolio-threlte\static\models\black_katana.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/black_katana.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="mech_me_-_animation">
      <T.Group name="Armature022">
        <T is={gltf.nodes.Hips} />
        <T is={gltf.nodes.Ctrl_Master} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Left} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Right} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Right} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Left} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Right} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Right} />
        <T.Group name="Wolf3D_Body006">
          <T.SkinnedMesh
            name="Wolf3D_Body005"
            geometry={gltf.nodes.Wolf3D_Body005.geometry}
            material={gltf.materials['Wolf3D_Body.008']}
            skeleton={gltf.nodes.Wolf3D_Body005.skeleton}
          />
          <T.SkinnedMesh
            name="Wolf3D_Body005_1"
            geometry={gltf.nodes.Wolf3D_Body005_1.geometry}
            material={gltf.materials.gloves}
            skeleton={gltf.nodes.Wolf3D_Body005_1.skeleton}
          />
        </T.Group>
        <T.SkinnedMesh
          name="Wolf3D_Hair005"
          geometry={gltf.nodes.Wolf3D_Hair005.geometry}
          material={gltf.materials['Wolf3D_Hair.009']}
          skeleton={gltf.nodes.Wolf3D_Hair005.skeleton}
        />
        <T.SkinnedMesh
          name="EyeLeft005"
          geometry={gltf.nodes.EyeLeft005.geometry}
          material={gltf.materials['Wolf3D_Eye.009']}
          skeleton={gltf.nodes.EyeLeft005.skeleton}
          morphTargetDictionary={gltf.nodes.EyeLeft005.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.EyeLeft005.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="EyeRight005"
          geometry={gltf.nodes.EyeRight005.geometry}
          material={gltf.materials['Wolf3D_Eye.009']}
          skeleton={gltf.nodes.EyeRight005.skeleton}
          morphTargetDictionary={gltf.nodes.EyeRight005.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.EyeRight005.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="Wolf3D_Teeth005"
          geometry={gltf.nodes.Wolf3D_Teeth005.geometry}
          material={gltf.materials['Wolf3D_Teeth.008']}
          skeleton={gltf.nodes.Wolf3D_Teeth005.skeleton}
          morphTargetDictionary={gltf.nodes.Wolf3D_Teeth005.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Wolf3D_Teeth005.morphTargetInfluences}
        />
      </T.Group>
      <T.Group name="glasses04objcleanermaterialmergergles" />
      <T.Group name="Wolf3D_Head017" />
      <T.Group name="Wolf3D_Head018" />
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Footwear009"
        geometry={gltf.nodes.Wolf3D_Outfit_Footwear009.geometry}
        material={gltf.materials['Wolf3D_Outfit_Footwear.012']}
        skeleton={gltf.nodes.Wolf3D_Outfit_Footwear009.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23002"
        geometry={gltf.nodes.Skin_ZSphere1_23002.geometry}
        material={gltf.materials.knee}
        skeleton={gltf.nodes.Skin_ZSphere1_23002.skeleton}
      />
      <T.SkinnedMesh
        name="Plane001"
        geometry={gltf.nodes.Plane001.geometry}
        material={gltf.materials['Wolf3D_Outfit_Top.010']}
        skeleton={gltf.nodes.Plane001.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23004"
        geometry={gltf.nodes.Skin_ZSphere1_23004.geometry}
        material={gltf.materials.knee}
        skeleton={gltf.nodes.Skin_ZSphere1_23004.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23006"
        geometry={gltf.nodes.Skin_ZSphere1_23006.geometry}
        material={gltf.materials['Wolf3D_Outfit_Bottom.014']}
        skeleton={gltf.nodes.Skin_ZSphere1_23006.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23007"
        geometry={gltf.nodes.Skin_ZSphere1_23007.geometry}
        material={gltf.materials['Wolf3D_Outfit_Bottom.014']}
        skeleton={gltf.nodes.Skin_ZSphere1_23007.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23008"
        geometry={gltf.nodes.Skin_ZSphere1_23008.geometry}
        material={gltf.materials['Wolf3D_Outfit_Bottom.014']}
        skeleton={gltf.nodes.Skin_ZSphere1_23008.skeleton}
      />
      <T.SkinnedMesh
        name="Skin_ZSphere1_23009"
        geometry={gltf.nodes.Skin_ZSphere1_23009.geometry}
        material={gltf.materials['Wolf3D_Outfit_Bottom.014']}
        skeleton={gltf.nodes.Skin_ZSphere1_23009.skeleton}
      />
      <T.SkinnedMesh
        name="Plane003"
        geometry={gltf.nodes.Plane003.geometry}
        material={gltf.materials.katana}
        skeleton={gltf.nodes.Plane003.skeleton}
      />
      <T.Group name="glasses">
        <T.SkinnedMesh
          name="Object_0001"
          geometry={gltf.nodes.Object_0001.geometry}
          material={gltf.materials['6666.001']}
          skeleton={gltf.nodes.Object_0001.skeleton}
        />
        <T.SkinnedMesh
          name="Object_0001_1"
          geometry={gltf.nodes.Object_0001_1.geometry}
          material={gltf.materials['7777.001']}
          skeleton={gltf.nodes.Object_0001_1.skeleton}
        />
        <T.SkinnedMesh
          name="Object_0001_2"
          geometry={gltf.nodes.Object_0001_2.geometry}
          material={gltf.materials['kanagu.001']}
          skeleton={gltf.nodes.Object_0001_2.skeleton}
        />
        <T.SkinnedMesh
          name="Object_0001_3"
          geometry={gltf.nodes.Object_0001_3.geometry}
          material={gltf.materials['steel01.001']}
          skeleton={gltf.nodes.Object_0001_3.skeleton}
        />
        <T.SkinnedMesh
          name="Object_0001_4"
          geometry={gltf.nodes.Object_0001_4.geometry}
          material={gltf.materials['steel2.001']}
          skeleton={gltf.nodes.Object_0001_4.skeleton}
        />
      </T.Group>
      <T.Group name="Wolf3D_Head007">
        <T.SkinnedMesh
          name="Wolf3D_Head014_1"
          geometry={gltf.nodes.Wolf3D_Head014_1.geometry}
          material={gltf.materials['Wolf3D_Skin.013']}
          skeleton={gltf.nodes.Wolf3D_Head014_1.skeleton}
          morphTargetDictionary={gltf.nodes.Wolf3D_Head014_1.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Wolf3D_Head014_1.morphTargetInfluences}
        />
        <T.SkinnedMesh
          name="Wolf3D_Head014_2"
          geometry={gltf.nodes.Wolf3D_Head014_2.geometry}
          material={gltf.materials.crease}
          skeleton={gltf.nodes.Wolf3D_Head014_2.skeleton}
          morphTargetDictionary={gltf.nodes.Wolf3D_Head014_2.morphTargetDictionary}
          morphTargetInfluences={gltf.nodes.Wolf3D_Head014_2.morphTargetInfluences}
        />
      </T.Group>
      <T.SkinnedMesh
        name="Wolf3D_Head008"
        geometry={gltf.nodes.Wolf3D_Head008.geometry}
        material={gltf.materials['Wolf3D_Skin.013']}
        skeleton={gltf.nodes.Wolf3D_Head008.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head008.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head008.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head009"
        geometry={gltf.nodes.Wolf3D_Head009.geometry}
        material={gltf.materials['Wolf3D_Skin.013']}
        skeleton={gltf.nodes.Wolf3D_Head009.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head009.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head009.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head010"
        geometry={gltf.nodes.Wolf3D_Head010.geometry}
        material={gltf.materials['Wolf3D_Skin.013']}
        skeleton={gltf.nodes.Wolf3D_Head010.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head010.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head010.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head011"
        geometry={gltf.nodes.Wolf3D_Head011.geometry}
        material={gltf.materials['Wolf3D_Skin.013']}
        skeleton={gltf.nodes.Wolf3D_Head011.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head011.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head011.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head012"
        geometry={gltf.nodes.Wolf3D_Head012.geometry}
        material={gltf.materials['Wolf3D_Skin.013']}
        skeleton={gltf.nodes.Wolf3D_Head012.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head012.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head012.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head013"
        geometry={gltf.nodes.Wolf3D_Head013.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head013.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head013.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head013.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head014"
        geometry={gltf.nodes.Wolf3D_Head014.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head014.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head014.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head014.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head015"
        geometry={gltf.nodes.Wolf3D_Head015.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head015.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head015.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head015.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head016"
        geometry={gltf.nodes.Wolf3D_Head016.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head016.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head016.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head016.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head019"
        geometry={gltf.nodes.Wolf3D_Head019.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head019.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head019.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head019.morphTargetInfluences}
      />
      <T.SkinnedMesh
        name="Wolf3D_Head020"
        geometry={gltf.nodes.Wolf3D_Head020.geometry}
        material={gltf.materials.mask}
        skeleton={gltf.nodes.Wolf3D_Head020.skeleton}
        morphTargetDictionary={gltf.nodes.Wolf3D_Head020.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head020.morphTargetInfluences}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
