<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\portfolio-threlte\static\models\me4.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/me4.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene002">
      <T.Group name="Armature006">
        <T is={gltf.nodes.mixamorig7Hips} />
        <T is={gltf.nodes.Ctrl_Master} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Left} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Right} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Right} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Left} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Right} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Right} />
        <T.SkinnedMesh
          name="Ch08_Body002"
          geometry={gltf.nodes.Ch08_Body002.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body002.skeleton}
        />
        <T.SkinnedMesh
          name="Ch08_Body003"
          geometry={gltf.nodes.Ch08_Body003.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body003.skeleton}
        />
        <T.SkinnedMesh
          name="Ch08_Body004"
          geometry={gltf.nodes.Ch08_Body004.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body004.skeleton}
        />
        <T.SkinnedMesh
          name="Ch08_Body005"
          geometry={gltf.nodes.Ch08_Body005.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body005.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={gltf.nodes.Wolf3D_Outfit_Bottom.geometry}
        material={gltf.materials.Wolf3D_Outfit_Bottom}
        skeleton={gltf.nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={gltf.nodes.Wolf3D_Outfit_Footwear.geometry}
        material={gltf.materials.Wolf3D_Outfit_Footwear}
        skeleton={gltf.nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Top002"
        geometry={gltf.nodes.Wolf3D_Outfit_Top002.geometry}
        material={gltf.materials['Wolf3D_Outfit_Top.004']}
        skeleton={gltf.nodes.Wolf3D_Outfit_Top002.skeleton}
      />
      <T.Group name="Ch45015">
        <T.SkinnedMesh
          name="Mesh046"
          geometry={gltf.nodes.Mesh046.geometry}
          material={gltf.materials['head.008']}
          skeleton={gltf.nodes.Mesh046.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh046_1"
          geometry={gltf.nodes.Mesh046_1.geometry}
          material={gltf.materials.disk}
          skeleton={gltf.nodes.Mesh046_1.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
