<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\portfolio-threlte\static\models\me_black.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/me_black.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="me_black">
      <T.Group name="Armature002">
        <T is={gltf.nodes.mixamorig7Hips} />
        <T is={gltf.nodes.Ctrl_Master} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Left} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Right} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Right} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Left} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Right} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Right} />
        <T.SkinnedMesh
          name="Ch08_Body008"
          geometry={gltf.nodes.Ch08_Body008.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body008.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Top001"
        geometry={gltf.nodes.Wolf3D_Outfit_Top001.geometry}
        material={gltf.materials['Wolf3D_Outfit_Top.004']}
        skeleton={gltf.nodes.Wolf3D_Outfit_Top001.skeleton}
      />
      <T.Group name="Ch45016">
        <T.SkinnedMesh
          name="Mesh006"
          geometry={gltf.nodes.Mesh006.geometry}
          material={gltf.materials['head.008']}
          skeleton={gltf.nodes.Mesh006.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_1"
          geometry={gltf.nodes.Mesh006_1.geometry}
          material={gltf.materials.disk}
          skeleton={gltf.nodes.Mesh006_1.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_2"
          geometry={gltf.nodes.Mesh006_2.geometry}
          material={gltf.materials.mask}
          skeleton={gltf.nodes.Mesh006_2.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_3"
          geometry={gltf.nodes.Mesh006_3.geometry}
          material={gltf.materials.glow}
          skeleton={gltf.nodes.Mesh006_3.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="0"
        geometry={gltf.nodes['0'].geometry}
        material={gltf.materials.Trousers}
        skeleton={gltf.nodes['0'].skeleton}
      />
      <T.SkinnedMesh
        name="7"
        geometry={gltf.nodes['7'].geometry}
        material={gltf.materials.Shoes}
        skeleton={gltf.nodes['7'].skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
