<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\artia-studio\static\models\crystal.gltf --root /models/ --printwidth 120 --precision 2
-->

<script>
    import { Group } from 'three'
    import { T, forwardEventHandlers, useThrelte } from '@threlte/core'
    import { useGltf, useGltfAnimations, Environment } from '@threlte/extras'
    import { onMount } from 'svelte';
    import * as THREE from 'three'
  
    export const ref = new Group()
  
    const { camera, scene, renderer } = useThrelte()
    const gltf = useGltf('/gltf/crystal/crystal.gltf')
    export const { actions, mixer } = useGltfAnimations(gltf, ref)
  
    const component = forwardEventHandlers()
    let crystal, envMap;
  
    onMount(() => {
      gltf.then(gltf => {
        console.log(gltf)
        crystal.material.envMapIntensity = 0.05
      })
    })
  </script>
  
  <T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
    {#await gltf}
      <slot name="fallback" />
    {:then gltf}
      <T.Group name="Scene">
        <T.Mesh name="defaultMaterial" bind:ref={crystal} geometry={gltf.nodes.defaultMaterial.geometry}
        material={gltf.materials['1001']}>
          <!-- <T.MeshPhysicalMaterial
            reflectivity={1}
            transmission={1}
            roughness={0}
            color={new THREE.Color(0x111111)}
          /> -->
        </T.Mesh>
      </T.Group>
    {:catch error}
      <slot name="error" {error} />
    {/await}
  
    <slot {ref} />
  </T>
  
  
  