<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\portfolio-threlte\static\models\me_black.glb --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { onDestroy, onMount } from 'svelte'
  import { useLoader, useThrelte } from '@threlte/core'
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, useTexture } from '@threlte/extras'
  import { hipHop, breakDance, idle } from '$lib/character.js'
  import * as THREE from 'three'

  export const ref = new Group()

  const gltf = useGltf('/models/me_black.glb')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()

  let currentActionKey = 'Idle'
    const { scene, camera, renderer } = useThrelte()

    $: console.log($gltf, actions)
  
    $: {
        if($actions && $actions[currentActionKey]){
            if(currentActionKey == 'Break Dance'){
                $actions[currentActionKey].loop = THREE.LoopPingPong
            }
            
            $actions[currentActionKey].play()
        }
    }
  
    const unsubIdle = idle.subscribe(() => {
      console.log('transition to idle')
      transitionTo('Idle', 0.3)
    })
  
    const unsubHipHop = hipHop.subscribe(() => {
      console.log('transition to hip hop')
      transitionTo('Hip Hop Dance', 0.3)
    })
  
    const unsubBreakDance = breakDance.subscribe(() => {
      console.log('transition to break dance')
      transitionTo('Break Dance', 0.3)
    })
  
    function transitionTo(nextActionKey, duration = 1) {
      const currentAction = $actions[currentActionKey]
      const nextAction = $actions[nextActionKey]
      if (!nextAction || currentAction === nextAction) return
      // Function inspired by: https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
      nextAction.enabled = true
      if (currentAction) {
        currentAction.crossFadeTo(nextAction, duration, true)
      }
      // Not sure why I need this but the source code does not
      nextAction.play()
      currentActionKey = nextActionKey
    }
  
    onDestroy(() => {
      // We unsubscribe otherwise we'd have old subscriptions still active
      unsubIdle()
      unsubHipHop()
      unsubBreakDance()
      scene.remove($gltf)
    })

    // Materials
    let topMaterial;
    let bottomMaterial; 
    let shoeMaterial;
    let headMaterial;
    const toonHead = useTexture('/toon.png')
    const blackHead = useTexture('/hair1.png')

    onMount(() => {
      gltf.then(value => {
        const top = value.materials['Wolf3D_Outfit_Top.004']
        const bottom = value.materials.Trousers
        const shoe = value.materials.Shoes
        const head = value.materials['head.008']
        // top.map = undefined;
        topMaterial = top
        // topMaterial = new THREE.MeshToonMaterial({  map: top.map, })
        // bottom.map = undefined;
        bottomMaterial = bottom;
        // bottomMaterial = new THREE.MeshToonMaterial({ map: bottom.map, color: 0xbbbbbb })
        shoeMaterial = shoe
        // shoeMaterial = new THREE.MeshToonMaterial({ map: shoe.map})
        // toonHead.then(headTexture => {
        //   headMaterial = new THREE.MeshToonMaterial({ map: head.map})
        // })

        blackHead.then(texture => {
          // texture = { ...head.map, source: texture.source}
          headMaterial = new THREE.MeshToonMaterial({ 
              map: head.map,
            })
          headMaterial = head
        })
        
      })
    })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="me_black">
      <T.Group name="Armature002">
        <T is={gltf.nodes.mixamorig7Hips} />
        <T is={gltf.nodes.Ctrl_Master} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Left} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Right} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Right} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Left} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Right} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Right} />
        <T.SkinnedMesh
          name="Ch08_Body008"
          geometry={gltf.nodes.Ch08_Body008.geometry}
          material={gltf.materials['Ch08_body.001']}
          skeleton={gltf.nodes.Ch08_Body008.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Top001"
        geometry={gltf.nodes.Wolf3D_Outfit_Top001.geometry}
        material={gltf.materials['Wolf3D_Outfit_Top.004']}
        skeleton={gltf.nodes.Wolf3D_Outfit_Top001.skeleton}
      />
      <T.Group name="Ch45016">
        <T.SkinnedMesh
          name="Mesh006"
          geometry={gltf.nodes.Mesh006.geometry}
          material={gltf.materials['head.008']}
          skeleton={gltf.nodes.Mesh006.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_1"
          geometry={gltf.nodes.Mesh006_1.geometry}
          material={gltf.materials.disk}
          skeleton={gltf.nodes.Mesh006_1.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_2"
          geometry={gltf.nodes.Mesh006_2.geometry}
          material={gltf.materials.mask}
          skeleton={gltf.nodes.Mesh006_2.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh006_3"
          geometry={gltf.nodes.Mesh006_3.geometry}
          material={gltf.materials.glow}
          skeleton={gltf.nodes.Mesh006_3.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="0"
        geometry={gltf.nodes['0'].geometry}
        material={bottomMaterial}
        skeleton={gltf.nodes['0'].skeleton}
      />
      <T.SkinnedMesh
        name="7"
        geometry={gltf.nodes['7'].geometry}
        material={shoeMaterial}
        skeleton={gltf.nodes['7'].skeleton}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
