<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 C:\Users\leduc\portfolio-threlte\static\models\me_white.gltf --root /models/ --printwidth 120 --precision 2
-->

<script>
  import { onDestroy, onMount } from 'svelte'
  import { useLoader, useThrelte } from '@threlte/core'
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations, useTexture } from '@threlte/extras'
  import { hipHop, breakDance, idle } from '$lib/character.js'
  import * as THREE from 'three'

  export const ref = new Group()

  const gltf = useGltf('/models/me_white.gltf')
  export const { actions, mixer } = useGltfAnimations(gltf, ref)
  
  const component = forwardEventHandlers()

  let currentActionKey = 'Idle'
    const { scene, camera, renderer } = useThrelte()

    $: console.log($gltf, actions)
  
    $: {
        if($actions && $actions[currentActionKey]){
            if(currentActionKey == 'Break Dance'){
                $actions[currentActionKey].loop = THREE.LoopPingPong
            }
            
            $actions[currentActionKey].play()
        }
    }
  
    const unsubIdle = idle.subscribe(() => {
      console.log('transition to idle')
      transitionTo('Idle', 0.3)
    })
  
    const unsubHipHop = hipHop.subscribe(() => {
      console.log('transition to hip hop')
      transitionTo('Hip Hop Dance', 0.3)
    })
  
    const unsubBreakDance = breakDance.subscribe(() => {
      console.log('transition to break dance')
      transitionTo('Break Dance', 0.3)
    })
  
    function transitionTo(nextActionKey, duration = 1) {
      const currentAction = $actions[currentActionKey]
      const nextAction = $actions[nextActionKey]
      if (!nextAction || currentAction === nextAction) return
      // Function inspired by: https://github.com/mrdoob/three.js/blob/master/examples/webgl_animation_skinning_blending.html
      nextAction.enabled = true
      if (currentAction) {
        currentAction.crossFadeTo(nextAction, duration, true)
      }
      // Not sure why I need this but the source code does not
      nextAction.play()
      currentActionKey = nextActionKey
    }
  
    onDestroy(() => {
      // We unsubscribe otherwise we'd have old subscriptions still active
      unsubIdle()
      unsubHipHop()
      unsubBreakDance()
      scene.remove($gltf)
    })

    // Materials
    let topMaterial;
    let bottomMaterial; 
    let shoeMaterial;
    let headMaterial;
    let handMaterial;
    const toonHead = useTexture('/toon.png')
    const blackHead = useTexture('/hair1.png')

    onMount(() => {
      gltf.then(value => {
        const top = value.materials['Wolf3D_Outfit_Top.004']
        const bottom = value.materials.Wolf3D_Outfit_Bottom
        const shoe = value.materials.Wolf3D_Outfit_Footwear
        const head = value.materials['head.008']
        const hand = value.materials['Ch08_body.001']
        // top.map = undefined;
        topMaterial = top
        // topMaterial = new THREE.MeshToonMaterial({  map: top.map, })
        // bottom.map = undefined;
        bottomMaterial = bottom;
        // bottomMaterial = new THREE.MeshToonMaterial({ map: bottom.map })
        shoeMaterial = shoe
        // shoeMaterial = new THREE.MeshToonMaterial({ map: shoe.map})
        toonHead.then(headTexture => {
          headMaterial = head
          // headMaterial = new THREE.MeshToonMaterial({ map: head.map})
        })
        handMaterial = hand
        // handMaterial = new THREE.MeshToonMaterial({ color: hand.color })

        // blackHead.then(texture => {
        //   // texture = { ...head.map, source: texture.source}
        //   headMaterial = new THREE.MeshToonMaterial({ 
        //       map: head.map,
        //     })
        //   headMaterial = head
        // })
        
      })
    })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene002">
      <T.Group name="Armature006">
        <T is={gltf.nodes.mixamorig7Hips} />
        <T is={gltf.nodes.Ctrl_Master} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Left} />
        <T is={gltf.nodes.Ctrl_ArmPole_IK_Right} />
        <T is={gltf.nodes.Ctrl_Hand_IK_Right} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Left} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Left} />
        <T is={gltf.nodes.Ctrl_Foot_IK_Right} />
        <T is={gltf.nodes.Ctrl_LegPole_IK_Right} />
       
        <T.SkinnedMesh
          name="Ch08_Body003"
          geometry={gltf.nodes.Ch08_Body003.geometry}
          material={handMaterial}
          skeleton={gltf.nodes.Ch08_Body003.skeleton}
        />
        <T.SkinnedMesh
          name="Ch08_Body005"
          geometry={gltf.nodes.Ch08_Body005.geometry}
          material={handMaterial}
          skeleton={gltf.nodes.Ch08_Body005.skeleton}
        />
      </T.Group>
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={gltf.nodes.Wolf3D_Outfit_Bottom.geometry}
        material={bottomMaterial}
        skeleton={gltf.nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={gltf.nodes.Wolf3D_Outfit_Footwear.geometry}
        material={shoeMaterial}
        skeleton={gltf.nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <T.SkinnedMesh
        name="Wolf3D_Outfit_Top002"
        geometry={gltf.nodes.Wolf3D_Outfit_Top002.geometry}
        material={topMaterial}
        skeleton={gltf.nodes.Wolf3D_Outfit_Top002.skeleton}
      />
      <T.Group name="Ch45015">
        <T.SkinnedMesh
          name="Mesh046"
          geometry={gltf.nodes.Mesh046.geometry}
          material={headMaterial}
          skeleton={gltf.nodes.Mesh046.skeleton}
        />
        <T.SkinnedMesh
          name="Mesh046_1"
          geometry={gltf.nodes.Mesh046_1.geometry}
          material={gltf.materials.disk}
          skeleton={gltf.nodes.Mesh046_1.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
